export const CONFIG = {
  githubUsername: 'npapatheodorou',
  contactEmail: 'n.papatheodorou@pm.me',
  headline: 'DevOps Engineer | Java • Spring • Quarkus | Secure, Scalable Systems',
  linkedIn: 'https://www.linkedin.com/in/npapatheodorou',
  name: 'Nikos Papatheodorou',
  title: 'DevOps Engineer',
  subtitle: 'Building Secure, Scalable, and Automated Systems',
};

export const NAV_ITEMS = [
  { id: 'overview', label: 'Overview' },
  { id: 'repositories', label: 'Repositories' },
  { id: 'skills', label: 'Skills' },
  { id: 'certifications', label: 'Certifications' },
  { id: 'projects', label: 'Projects' },
  { id: 'contributions', label: 'Contributions' },
  { id: 'publications', label: 'Publications' },
  { id: 'research', label: 'Research' },
  { id: 'career', label: 'Career' },
  { id: 'contact', label: 'Contact' },
];

export const SKILLS_DATA = {
  backend: {
    title: 'Backend Development',
    icon: 'server',
    color: 'from-blue-500 to-blue-700',
    skills: [
      { name: 'Java', level: 95, years: 6, category: 'Language' },
      { name: 'Spring Framework', level: 92, years: 5, category: 'Framework' },
      { name: 'Spring Boot', level: 90, years: 5, category: 'Framework' },
      { name: 'Quarkus', level: 85, years: 3, category: 'Framework' },
      { name: 'REST API Design', level: 90, years: 6, category: 'Architecture' },
      { name: 'Microservices', level: 88, years: 4, category: 'Architecture' },
      { name: 'Hibernate/JPA', level: 87, years: 5, category: 'ORM' },
      { name: 'Maven/Gradle', level: 88, years: 6, category: 'Build Tools' },
    ],
  },
  devops: {
    title: 'DevOps & Infrastructure',
    icon: 'settings',
    color: 'from-green-500 to-emerald-700',
    skills: [
      { name: 'CI/CD Pipelines', level: 90, years: 4, category: 'Automation' },
      { name: 'Docker', level: 92, years: 5, category: 'Containerization' },
      { name: 'Kubernetes', level: 85, years: 3, category: 'Orchestration' },
      { name: 'Terraform', level: 82, years: 3, category: 'IaC' },
      { name: 'Ansible', level: 80, years: 3, category: 'Configuration' },
      { name: 'Jenkins', level: 88, years: 4, category: 'CI/CD' },
      { name: 'GitHub Actions', level: 87, years: 3, category: 'CI/CD' },
      { name: 'GitLab CI', level: 85, years: 3, category: 'CI/CD' },
      { name: 'AWS', level: 82, years: 3, category: 'Cloud' },
      { name: 'Linux Administration', level: 88, years: 6, category: 'Systems' },
    ],
  },
  performance: {
    title: 'Performance & Reliability',
    icon: 'zap',
    color: 'from-amber-500 to-orange-600',
    skills: [
      { name: 'Database Optimization', level: 85, years: 4, category: 'Database' },
      { name: 'PostgreSQL', level: 87, years: 5, category: 'Database' },
      { name: 'Redis Caching', level: 83, years: 3, category: 'Caching' },
      { name: 'System Monitoring', level: 85, years: 4, category: 'Observability' },
      { name: 'Prometheus/Grafana', level: 82, years: 3, category: 'Monitoring' },
      { name: 'ELK Stack', level: 78, years: 2, category: 'Logging' },
      { name: 'Load Testing', level: 80, years: 3, category: 'Testing' },
      { name: 'High Availability Design', level: 82, years: 3, category: 'Architecture' },
    ],
  },
  security: {
    title: 'Security',
    icon: 'shield',
    color: 'from-red-500 to-rose-700',
    skills: [
      { name: 'Secure Architecture', level: 85, years: 4, category: 'Design' },
      { name: 'OAuth2/OIDC', level: 83, years: 3, category: 'Auth' },
      { name: 'JWT/Token Management', level: 85, years: 4, category: 'Auth' },
      { name: 'Blockchain/SSI', level: 80, years: 2, category: 'Research' },
      { name: 'SAST/DAST Integration', level: 78, years: 2, category: 'DevSecOps' },
      { name: 'Secret Management', level: 82, years: 3, category: 'Security' },
      { name: 'Network Security', level: 78, years: 3, category: 'Infrastructure' },
    ],
  },
  research: {
    title: 'Research & Teaching',
    icon: 'book',
    color: 'from-purple-500 to-violet-700',
    skills: [
      { name: 'C Programming', level: 80, years: 4, category: 'Language' },
      { name: 'Python', level: 82, years: 4, category: 'Language' },
      { name: 'Academic Writing', level: 85, years: 3, category: 'Research' },
      { name: 'Technical Mentoring', level: 88, years: 4, category: 'Teaching' },
      { name: 'Workshop Facilitation', level: 85, years: 3, category: 'Teaching' },
    ],
  },
};

export const PROJECTS_DATA = [
  {
    id: 1,
    title: 'Enterprise CI/CD Pipeline Modernization',
    category: 'DevOps',
    challenge: 'Legacy deployment process with 4-hour release cycles, frequent rollback failures, and zero automated testing in the pipeline.',
    solution: 'Designed and implemented a full GitOps-based CI/CD pipeline using Jenkins, Docker, and Kubernetes with automated quality gates, security scanning, and blue-green deployments.',
    architecture: [
      'Multi-stage Jenkins pipelines with shared libraries',
      'Docker multi-stage builds for optimized images',
      'Kubernetes rolling updates with health checks',
      'Integrated SonarQube, OWASP ZAP, and Trivy scanning',
      'Automated rollback with canary analysis',
    ],
    tools: ['Jenkins', 'Docker', 'Kubernetes', 'SonarQube', 'Helm', 'ArgoCD'],
    results: [
      { metric: 'Deployment Time', before: '4 hours', after: '12 minutes', improvement: '95%' },
      { metric: 'Release Frequency', before: 'Monthly', after: 'Daily', improvement: '30x' },
      { metric: 'Rollback Success', before: '60%', after: '99.5%', improvement: '66%' },
      { metric: 'Security Vulns', before: 'Unknown', after: 'Zero Critical', improvement: '100%' },
    ],
    icon: 'rocket',
    gradient: 'from-blue-600 to-cyan-500',
  },
  {
    id: 2,
    title: 'High-Performance Spring Boot Microservices',
    category: 'Backend',
    challenge: 'Monolithic application handling 10K+ concurrent users with 3-second average response times and frequent OOM crashes under peak load.',
    solution: 'Decomposed monolith into Spring Boot microservices with proper domain boundaries, implemented Redis caching, database read replicas, and async processing.',
    architecture: [
      'Domain-Driven Design for service boundaries',
      'Spring Cloud Gateway for API routing',
      'Redis cluster for distributed caching',
      'PostgreSQL with read replicas and connection pooling',
      'RabbitMQ for async event processing',
    ],
    tools: ['Spring Boot', 'Redis', 'PostgreSQL', 'RabbitMQ', 'Docker', 'Kubernetes'],
    results: [
      { metric: 'Response Time (p95)', before: '3.2s', after: '180ms', improvement: '94%' },
      { metric: 'Concurrent Users', before: '10K', after: '100K+', improvement: '10x' },
      { metric: 'Uptime', before: '99.2%', after: '99.95%', improvement: '99.95%' },
      { metric: 'Memory Usage', before: '16GB', after: '4GB/service', improvement: '75%' },
    ],
    icon: 'zap',
    gradient: 'from-green-600 to-emerald-500',
  },
  {
    id: 3,
    title: 'Infrastructure as Code Automation',
    category: 'Infrastructure',
    challenge: 'Manual server provisioning taking 2-3 days per environment with configuration drift causing production incidents monthly.',
    solution: 'Implemented complete IaC using Terraform for cloud provisioning and Ansible for configuration management, with environment parity enforcement.',
    architecture: [
      'Terraform modules for reusable infrastructure components',
      'Ansible roles for application configuration',
      'GitOps workflow for infrastructure changes',
      'Automated compliance scanning with InSpec',
      'Environment promotion pipeline (dev → staging → prod)',
    ],
    tools: ['Terraform', 'Ansible', 'AWS', 'GitLab CI', 'InSpec', 'Vault'],
    results: [
      { metric: 'Provisioning Time', before: '2-3 days', after: '45 minutes', improvement: '97%' },
      { metric: 'Config Drift', before: '4/month', after: '0/month', improvement: '100%' },
      { metric: 'Environment Parity', before: 'Low', after: '100%', improvement: '100%' },
      { metric: 'Cost Optimization', before: 'N/A', after: '35% reduction', improvement: '35%' },
    ],
    icon: 'layers',
    gradient: 'from-purple-600 to-violet-500',
  },
  {
    id: 4,
    title: 'Secure Authentication & Identity Platform',
    category: 'Security',
    challenge: 'Fragmented authentication across 12 services with inconsistent security policies and no centralized audit logging.',
    solution: 'Built centralized identity platform with OAuth2/OIDC, incorporating SSI research concepts for user-controlled data, with complete audit trail.',
    architecture: [
      'Keycloak-based identity provider with custom extensions',
      'OAuth2 Authorization Code flow with PKCE',
      'JWT token management with rotation policies',
      'Centralized audit logging with tamper detection',
      'GDPR-compliant consent management',
    ],
    tools: ['Keycloak', 'Spring Security', 'JWT', 'PostgreSQL', 'ELK Stack', 'Vault'],
    results: [
      { metric: 'Auth Incidents', before: '8/quarter', after: '0/quarter', improvement: '100%' },
      { metric: 'GDPR Compliance', before: 'Partial', after: 'Full', improvement: '100%' },
      { metric: 'SSO Coverage', before: '30%', after: '100%', improvement: '233%' },
      { metric: 'Token Latency', before: '800ms', after: '45ms', improvement: '94%' },
    ],
    icon: 'shield',
    gradient: 'from-red-600 to-rose-500',
  },
  {
    id: 5,
    title: 'Observability & Monitoring Platform',
    category: 'Reliability',
    challenge: 'Zero visibility into system health, MTTR of 4+ hours for incidents, and no proactive alerting.',
    solution: 'Implemented comprehensive observability stack with metrics, logging, and distributed tracing, with intelligent alerting.',
    architecture: [
      'Prometheus for metrics collection with custom exporters',
      'Grafana dashboards with SLO/SLI tracking',
      'ELK Stack for centralized logging',
      'Jaeger for distributed tracing',
      'PagerDuty integration with escalation policies',
    ],
    tools: ['Prometheus', 'Grafana', 'ELK Stack', 'Jaeger', 'PagerDuty', 'AlertManager'],
    results: [
      { metric: 'MTTR', before: '4+ hours', after: '18 minutes', improvement: '93%' },
      { metric: 'Proactive Detection', before: '0%', after: '85%', improvement: '85%' },
      { metric: 'Dashboard Coverage', before: '0', after: '45 dashboards', improvement: '∞' },
      { metric: 'Alert Noise', before: 'N/A', after: '<5% false positive', improvement: '95%' },
    ],
    icon: 'activity',
    gradient: 'from-amber-600 to-yellow-500',
  },
  {
    id: 6,
    title: 'Quarkus Cloud-Native Migration',
    category: 'Backend',
    challenge: 'Spring Boot services with 30-second startup times and 512MB+ memory footprint, causing slow auto-scaling.',
    solution: 'Migrated critical path services to Quarkus with GraalVM native compilation, achieving sub-second startup.',
    architecture: [
      'Quarkus with GraalVM native-image compilation',
      'RESTEasy Reactive for non-blocking I/O',
      'Hibernate Reactive with Vert.x SQL client',
      'SmallRye Config for 12-factor app configuration',
      'Kubernetes-native health checks and scaling',
    ],
    tools: ['Quarkus', 'GraalVM', 'Kubernetes', 'Vert.x', 'Docker', 'Helm'],
    results: [
      { metric: 'Startup Time', before: '30 seconds', after: '0.8 seconds', improvement: '97%' },
      { metric: 'Memory Usage', before: '512MB', after: '64MB', improvement: '87%' },
      { metric: 'Cloud Costs', before: 'Baseline', after: '60% reduction', improvement: '60%' },
      { metric: 'Auto-Scale', before: '45 seconds', after: '3 seconds', improvement: '93%' },
    ],
    icon: 'cpu',
    gradient: 'from-teal-600 to-cyan-500',
  },
];

export const CAREER_DATA = [
  {
    id: 1,
    title: 'DevOps Developer',
    company: 'Ernst & Young (EY)',
    employmentType: 'Full-time',
    period: 'Jul 2024 - Present',
    duration: '1 yr 8 mos',
    location: 'Athens, Attiki, Greece - Hybrid',
    type: 'current',
    logo: 'ey',
    summary: 'Building and maintaining CI/CD workflows, deployment automation, and cloud-native delivery pipelines for enterprise services.',
    highlights: [
      'Designed and improved CI/CD pipelines for faster and safer releases',
      'Automated environment provisioning and deployment workflows',
      'Supported reliable operations across development and production environments',
    ],
    technologies: ['Azure', 'CI/CD', 'Docker', 'Kubernetes', 'Terraform', 'Java', 'Spring Boot'],
  },
  {
    id: 2,
    title: 'Back-end Software Engineer',
    company: 'APT Information Systems',
    employmentType: 'Full-time',
    period: 'Jan 2021 - Jun 2024',
    duration: '3 yrs 6 mos',
    location: 'Athens, Attiki, Greece',
    type: 'past',
    logo: 'apt',
    summary: 'Developed and maintained backend systems with Spring Framework and Java for production business applications.',
    highlights: [
      'Built backend APIs and business services using Java and Spring technologies',
      'Collaborated on architecture, implementation, and maintenance of core systems',
      'Delivered stable features and improvements across multiple product releases',
    ],
    technologies: ['Java', 'Spring Framework', 'Spring Boot', 'REST APIs', 'SQL', 'Hibernate/JPA'],
  },
  {
    id: 3,
    title: 'Academic Tutor',
    company: 'Hellenic Mediterranean University',
    employmentType: 'Academic',
    period: 'Oct 2019 - Feb 2021',
    duration: '1 yr 5 mos',
    location: 'Heraklion, Crete, Greece',
    type: 'academic',
    logo: 'hmu',
    summary: 'Consolidated concurrent tutoring roles into one academic position, supporting undergraduate teaching across core informatics modules.',
    highlights: [
      'Delivered labs, tutorials, and student support across multiple courses',
      'Prepared educational material and guided students through practical exercises',
    ],
    courses: [
      'Information Systems Security (TP-122)',
      'Algorithms (TP-313)',
      'Databases (TP-132)',
      'Object Oriented Programming (ECE-136)',
      'Scientific Programming with Python (ECE-102)',
      'Programming Languages (TP-338)',
      'Modern Topics in Informatics (TP-105)',
    ],
    technologies: ['Teaching', 'Java', 'Python', 'Databases', 'Algorithms', 'Programming Languages'],
  },
];

export const RESEARCH_DATA = {
  thesis: {
    title: 'Blockchain-based Self-Sovereign Identity (SSI)',
    degree: 'Master of Science',
    description: 'Researched and implemented a decentralized identity management system leveraging blockchain technology to give users full control over their digital identities, eliminating reliance on centralized identity providers.',
    contributions: [
      'Designed a novel SSI architecture using distributed ledger technology',
      'Implemented proof-of-concept with verifiable credentials',
      'Analyzed security properties including privacy, integrity, and availability',
      'Evaluated performance characteristics against traditional identity systems',
      'Published findings with recommendations for enterprise adoption',
    ],
    keywords: ['Blockchain', 'Self-Sovereign Identity', 'Decentralized Identity', 'Verifiable Credentials', 'DID', 'Privacy'],
  },
  presentations: [
    {
      title: 'Linaro Connect Workshop',
      venue: 'Linaro Connect Conference',
      type: 'Workshop',
      description: 'Led a hands-on workshop on embedded systems development and Linux-based toolchains for IoT devices.',
    },
    {
      title: 'Blockchain Identity Research',
      venue: 'Academic Conference',
      type: 'Presentation',
      description: 'Presented MSc thesis findings on blockchain-based identity systems and their applicability to enterprise environments.',
    },
  ],
  teaching: [
    {
      course: 'Java Programming',
      level: 'Undergraduate',
      description: 'Taught object-oriented programming principles, data structures, and software design patterns using Java.',
    },
    {
      course: 'C Programming',
      level: 'Undergraduate',
      description: 'Instructed systems programming, memory management, and low-level programming concepts in C.',
    },
    {
      course: 'Python Programming',
      level: 'Undergraduate',
      description: 'Taught scripting, data manipulation, and introductory algorithms using Python.',
    },
  ],
};

export const PUBLICATIONS_DATA = [
  {
    id: 1,
    title: 'The YouGovern Secure Blockchain-Based Self-Sovereign Identity (SSI) Management and Access Control',
    authors: 'Nikolaos Papatheodorou et al.',
    venue: 'MDPI Applied Sciences',
    venueShort: 'Applied Sciences',
    volume: '15(12), 6437',
    publisher: 'MDPI',
    date: 'June 7, 2025',
    year: 2025,
    doi: null,
    url: 'https://www.mdpi.com/2076-3417/15/12/6437',
    type: 'Journal Article',
    tags: ['Blockchain', 'Self-Sovereign Identity', 'Access Control', 'Security', 'Decentralized Identity'],
    abstract: 'Presents a secure blockchain-based Self-Sovereign Identity (SSI) management system with robust access control mechanisms, enabling users to maintain full ownership of their digital identities without relying on centralized authorities.',
    color: 'from-purple-600 to-violet-500',
    icon: 'journal',
  },
  {
    id: 2,
    title: 'Secure Authentication in the Presence of Malicious Messages and Packet Reorders: Study on CAN Bus',
    authors: 'Nikolaos Papatheodorou et al.',
    venue: '2025 IEEE 15th Annual Computing and Communication Workshop and Conference (CCWC)',
    venueShort: 'IEEE CCWC 2025',
    volume: null,
    publisher: 'IEEE',
    date: 'March 5, 2025',
    year: 2025,
    doi: '10.1109/CCWC62904.2025.10903953',
    url: 'https://ieeexplore.ieee.org/document/10903953',
    type: 'Conference Paper',
    tags: ['CAN Bus', 'Automotive Security', 'Authentication', 'Embedded Systems', 'Network Security'],
    abstract: 'Investigates secure authentication protocols for Controller Area Network (CAN) bus systems under adversarial conditions, addressing malicious message injection and packet reordering attacks in vehicular networks.',
    color: 'from-blue-600 to-cyan-500',
    icon: 'conference',
  },
  {
    id: 3,
    title: 'DoS Detection on In-Vehicle Networks: Evaluation on an Experimental Embedded System Platform',
    authors: 'Nikolaos Papatheodorou et al.',
    venue: 'Applications in Electronics Pervading Industry, Environment and Society (ApplePies 2021)',
    venueShort: 'ApplePies 2021',
    volume: 'Lecture Notes in Electrical Engineering, vol 866',
    publisher: 'Springer',
    date: 'April 9, 2022',
    year: 2022,
    doi: '10.1007/978-3-030-95498-7_37',
    url: 'https://link.springer.com/chapter/10.1007/978-3-030-95498-7_37',
    type: 'Book Chapter',
    tags: ['DoS Detection', 'In-Vehicle Networks', 'Embedded Systems', 'Intrusion Detection', 'CAN Bus'],
    abstract: 'Evaluates Denial-of-Service detection mechanisms for in-vehicle networks using an experimental embedded system platform, demonstrating practical approaches to securing automotive communication systems.',
    color: 'from-green-600 to-emerald-500',
    icon: 'book',
  },
  {
    id: 4,
    title: 'A Probabilistic Logic Program that Predicts COVID-19 Infection and the Possibility a Patient to Recover',
    authors: 'Nikolaos Papatheodorou et al.',
    venue: '24th Pan-Hellenic Conference on Informatics (PCI 2020)',
    venueShort: 'PCI 2020',
    volume: null,
    publisher: 'ACM',
    date: 'November 20, 2020',
    year: 2020,
    doi: '10.1145/3437120.3437323',
    url: 'https://dl.acm.org/doi/10.1145/3437120.3437323',
    type: 'Conference Paper',
    tags: ['Probabilistic Logic', 'COVID-19', 'Machine Learning', 'Healthcare', 'Prediction'],
    abstract: 'Develops a probabilistic logic programming approach for predicting COVID-19 infection likelihood and patient recovery probability, combining logical reasoning with probabilistic inference for healthcare decision support.',
    color: 'from-amber-600 to-orange-500',
    icon: 'conference',
  },
];

export const CERTIFICATIONS_DATA = [
  {
    id: 1,
    title: 'Microsoft Certified: Azure Administrator Associate',
    issuer: 'Microsoft',
    issued: 'February 2026',
    expires: 'February 2027',
    credentialId: '60626A10BBAAAAF1',
    url: 'https://learn.microsoft.com/en-us/users/nikospapatheodorou-7173/credentials/60626a10bbaaaaf1',
    logo: 'microsoft',
    color: 'from-blue-500 to-cyan-500',
    bgColor: 'bg-blue-500',
    tags: ['Azure', 'Cloud', 'Infrastructure', 'Administration'],
    description: 'Validates expertise in implementing, managing, and monitoring Azure environments including virtual networks, storage, compute, identity, security, and governance.',
    level: 'Associate',
    status: 'active',
  },
  {
    id: 2,
    title: 'AWS Certified Cloud Practitioner',
    issuer: 'Amazon Web Services (AWS)',
    issued: 'February 2026',
    expires: 'February 2029',
    credentialId: '0596115d166442fc96f08325de4f2992',
    url: 'https://www.credly.com/badges/a55933c0-a47d-47e1-a082-5fbc9bb545a8',
    logo: 'aws',
    color: 'from-amber-500 to-orange-500',
    bgColor: 'bg-amber-500',
    tags: ['AWS', 'Cloud', 'Architecture', 'Services'],
    description: 'Demonstrates foundational understanding of AWS Cloud concepts, services, security, architecture, pricing, and support to build cloud fluency.',
    level: 'Foundational',
    status: 'active',
  },
  {
    id: 3,
    title: 'Certified Vaadin 24 Developer',
    issuer: 'Vaadin',
    issued: 'February 2026',
    expires: null,
    credentialId: '#5a033b87-83e3-491e-b28f-ba14a3a3dc79',
    url: 'https://vaadin.com/learn/certificate/5a033b87-83e3-491e-b28f-ba14a3a3dc79',
    logo: 'vaadin',
    color: 'from-cyan-500 to-blue-600',
    bgColor: 'bg-cyan-600',
    tags: ['Java', 'Web Framework', 'Full-Stack', 'UI Development'],
    description: 'Certifies proficiency in building modern web applications using the Vaadin 24 framework with Java-based full-stack development capabilities.',
    level: 'Professional',
    status: 'active',
  },
  {
    id: 4,
    title: 'Oracle Certified Professional: Java SE 17 Developer',
    issuer: 'Oracle',
    issued: 'October 2023',
    expires: null,
    credentialId: '100072762OCPJSE17',
    url: 'https://catalog-education.oracle.com/ords/certview/sharebadge?id=3B1662C516A0423B37904FF9E7349892FF420C6F54F49008143EE2D814F6D72E',
    logo: 'oracle',
    color: 'from-red-500 to-red-700',
    bgColor: 'bg-red-600',
    tags: ['Java', 'SE 17', 'OOP', 'Core Java'],
    description: 'Validates advanced Java programming skills including modules, concurrency, I/O, annotations, generics, and the Java platform module system in Java SE 17.',
    level: 'Professional',
    status: 'active',
  },
  {
    id: 5,
    title: 'Certified Vaadin 14 Developer',
    issuer: 'Vaadin',
    issued: 'March 2021',
    expires: null,
    credentialId: '#9e156ab3-a996-4365-9694-871c6ee6016d',
    url: 'https://vaadin.com/learn/certificate/9e156ab3-a996-4365-9694-871c6ee6016d',
    logo: 'vaadin',
    color: 'from-teal-500 to-cyan-600',
    bgColor: 'bg-teal-600',
    tags: ['Java', 'Web Framework', 'Full-Stack', 'UI Development'],
    description: 'Certifies proficiency in building web applications using the Vaadin 14 framework with Java-based component architecture.',
    level: 'Professional',
    status: 'active',
  },
];

export const LANGUAGE_COLORS = {
  Java: '#b07219',
  JavaScript: '#f1e05a',
  Python: '#3572A5',
  C: '#555555',
  'C++': '#f34b7d',
  Go: '#00ADD8',
  TypeScript: '#3178c6',
  Shell: '#89e051',
  Dockerfile: '#384d54',
  HCL: '#844FBA',
  Kotlin: '#A97BFF',
  Groovy: '#4298b8',
  HTML: '#e34c26',
  CSS: '#563d7c',
  YAML: '#cb171e',
  Makefile: '#427819',
};

export const STATS_OVERVIEW = [
  { label: 'Years Experience', value: '6+', icon: 'calendar', color: 'text-blue-400' },
  { label: 'Publications', value: '4', icon: 'server', color: 'text-green-400' },
  { label: 'Uptime Achieved', value: '99.95%', icon: 'activity', color: 'text-amber-400' },
  { label: 'Deploy Reduction', value: '95%', icon: 'rocket', color: 'text-purple-400' },
];
